<a href="https://colab.research.google.com/github/JUMAAMOS/Business-Analytics-Python/blob/main/Iris_data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

:# **Data Preprocessing using scikit-learn (sklearn) in Python**

---



In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files

select iris.csv

In [3]:
files.upload()

Saving Iris.csv to Iris.csv


{'Iris.csv': b'Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species\n1,5.1,3.5,1.4,0.2,Iris-setosa\n2,4.9,3.0,1.4,0.2,Iris-setosa\n3,4.7,3.2,1.3,0.2,Iris-setosa\n4,4.6,3.1,1.5,0.2,Iris-setosa\n5,5.0,3.6,1.4,0.2,Iris-setosa\n6,5.4,3.9,1.7,0.4,Iris-setosa\n7,4.6,3.4,1.4,0.3,Iris-setosa\n8,5.0,3.4,1.5,0.2,Iris-setosa\n9,4.4,2.9,1.4,0.2,Iris-setosa\n10,4.9,3.1,1.5,0.1,Iris-setosa\n11,5.4,3.7,1.5,0.2,Iris-setosa\n12,4.8,3.4,1.6,0.2,Iris-setosa\n13,4.8,3.0,1.4,0.1,Iris-setosa\n14,4.3,3.0,1.1,0.1,Iris-setosa\n15,5.8,4.0,1.2,0.2,Iris-setosa\n16,5.7,4.4,1.5,0.4,Iris-setosa\n17,5.4,3.9,1.3,0.4,Iris-setosa\n18,5.1,3.5,1.4,0.3,Iris-setosa\n19,5.7,3.8,1.7,0.3,Iris-setosa\n20,5.1,3.8,1.5,0.3,Iris-setosa\n21,5.4,3.4,1.7,0.2,Iris-setosa\n22,5.1,3.7,1.5,0.4,Iris-setosa\n23,4.6,3.6,1.0,0.2,Iris-setosa\n24,5.1,3.3,1.7,0.5,Iris-setosa\n25,4.8,3.4,1.9,0.2,Iris-setosa\n26,5.0,3.0,1.6,0.2,Iris-setosa\n27,5.0,3.4,1.6,0.4,Iris-setosa\n28,5.2,3.5,1.5,0.2,Iris-setosa\n29,5.2,3.4,1.4,0.2,Iris-setosa\n

In [4]:
!ls

Iris.csv  sample_data


In [5]:
df = pd.read_csv('Iris.csv', header=0, index_col=0)

In [7]:
cols=df.columns
print(cols)

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')


In [8]:
df.shape

(150, 5)

In [9]:
rows=df.index

In [ ]:
print(rows)

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
      dtype='int64', name='Id', length=150)


In [10]:
from sklearn import preprocessing

In [11]:
X = df[cols[:-1]]

In [12]:
X.shape

(150, 4)

In [13]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                           
1              5.1           3.5            1.4           0.2
2              4.9           3.0            1.4           0.2
3              4.7           3.2            1.3           0.2
4              4.6           3.1            1.5           0.2
5              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
146            6.7           3.0            5.2           2.3
147            6.3           2.5            5.0           1.9
148            6.5           3.0            5.2           2.0
149            6.2           3.4            5.4           2.3
150            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [15]:
y=df[cols[-1]]

In [16]:
y.shape

(150,)

In [18]:
y

Id
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
            ...      
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
150    Iris-virginica
Name: Species, Length: 150, dtype: object

***Binary Scaler: ***
Data converted to 0 or 1 based on threhold value

Example greater than two is 1 (True) and two or less is 0 (False)

In [19]:
data_binarizer = preprocessing.Binarizer(threshold=2)
data_binarized = data_binarizer.fit_transform(X)
print("\nBinarized data:\n", data_binarized[:5])


Binarized data:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


***Min Max Scaler: *** *italicized text*
Data converted to a range of 0 to 1

The maximum data value gets 1 and the minimum value is 0 and other data is converted to a range between 0 and 1

In [20]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(X)
print ("\nMin max scaled data:\n", data_scaled_minmax[:5].round(2))


Min max scaled data:
 [[0.22 0.62 0.07 0.04]
 [0.17 0.42 0.07 0.04]
 [0.11 0.5  0.05 0.04]
 [0.08 0.46 0.08 0.04]
 [0.19 0.67 0.07 0.04]]


***Max Absolute Scaler: ***
Absolute Value normalization
Data converted to a range of -1 to 1

The maximum absoulte data value gets 1 or -1 and other data is converted to a range between -1 and 1

In [ ]:
data_scaler_maxabs = preprocessing.MaxAbsScaler()
data_scaled_maxabs = data_scaler_maxabs.fit_transform(X)
print ("\nAbsolute Value Normalization (Max Absolute Scale):\n", data_scaled_minmax[:5].round(2))


Absolute Value Normalization (Max Absolute Scale):
 [[0.22 0.62 0.07 0.04]
 [0.17 0.42 0.07 0.04]
 [0.11 0.5  0.05 0.04]
 [0.08 0.46 0.08 0.04]
 [0.19 0.67 0.07 0.04]]


**Standard Scaler: **
Data converted to a range of -1 to 1

StandardScaler makes sure that input variables have a mean of about 0 and a standard deviation of about 1

This process is known as Normalization

In [ ]:
data_standard_scaler= preprocessing.StandardScaler()
data_standard_scaled=data_standard_scaler.fit_transform(X)
print("\nStandardized data:\n", data_standard_scaled[:5].round(2))


Standardized data:
 [[-0.9   1.03 -1.34 -1.31]
 [-1.14 -0.12 -1.34 -1.31]
 [-1.39  0.34 -1.4  -1.31]
 [-1.51  0.11 -1.28 -1.31]
 [-1.02  1.26 -1.34 -1.31]]


***Roboust Scaler: ***
Similar to Standard Scaler but is based on Median and Inter Quartile Range
Calculates the median of each feature.
Determines the IQR (range between the 1st and 3rd quartiles).
Centers the data by subtracting the median from each value.
Scales the data by dividing the centered values by the IQR.

A Robust Scaler is particularly good for datasets that contain a significant number of outliers, as it uses the median and interquartile range (IQR) to scale data, which are less sensitive to extreme values

In [ ]:
data_robust_scaler= preprocessing.RobustScaler()
data_robust_scaled=data_standard_scaler.fit_transform(X)
print("\nRobust scale data:\n", data_robust_scaled[:5].round(2))


Robust scale data:
 [[-0.9   1.03 -1.34 -1.31]
 [-1.14 -0.12 -1.34 -1.31]
 [-1.39  0.34 -1.4  -1.31]
 [-1.51  0.11 -1.28 -1.31]
 [-1.02  1.26 -1.34 -1.31]]


**One Hot Encoding vs Label Encoding**
Machine Learning techniques for converting categorical data into numerical format.

Label Encoding is a technique that is used to convert categorical columns into numerical ones so that they can be fitted by machine learning models which only take numerical data.


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the Series
encoded_df = label_encoder.fit_transform(y)
# Create a DataFrame from the encoded array
encoded_df = pd.DataFrame(encoded_df,columns=["Species"],  index=X.index)
result_df = pd.concat([X, encoded_df], axis=1)
print(result_df)


     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
1              5.1           3.5            1.4           0.2        0
2              4.9           3.0            1.4           0.2        0
3              4.7           3.2            1.3           0.2        0
4              4.6           3.1            1.5           0.2        0
5              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
146            6.7           3.0            5.2           2.3        2
147            6.3           2.5            5.0           1.9        2
148            6.5           3.0            5.2           2.0        2
149            6.2           3.4            5.4           2.3        2
150            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]


**One Hot Encoding**
Various Machine Learning models do not work with categorical data and to fit this data into the machine learning model it needs to be converted into numerical data. For example, suppose a dataset has a Gender column with categorical elements like Male and  Female. These labels have no specific order of preference and also since the data is string labels, machine learning models misinterpreted that there is some sort of hierarchy in them.

To address this issue, one effective technique is one hot encoding. OHE in machine learning transforms categorical data into a numerical format that machine learning algorithms can process without imposing any ordinal relationships.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)  # Use dense output for easier handling
# Fit and transform the Series
encoded_array = encoder.fit_transform(y.values.reshape(-1, 1))
# Create a DataFrame from the encoded array
encoded_df = pd.DataFrame(encoded_array, columns=encoder.categories_[0], index=X.index)
# Combine the original Series with the one-hot encoded DataFrame
result_df = pd.concat([X, encoded_df],axis=1)
print(result_df)



     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Iris-setosa  \
Id                                                                           
1              5.1           3.5            1.4           0.2          1.0   
2              4.9           3.0            1.4           0.2          1.0   
3              4.7           3.2            1.3           0.2          1.0   
4              4.6           3.1            1.5           0.2          1.0   
5              5.0           3.6            1.4           0.2          1.0   
..             ...           ...            ...           ...          ...   
146            6.7           3.0            5.2           2.3          0.0   
147            6.3           2.5            5.0           1.9          0.0   
148            6.5           3.0            5.2           2.0          0.0   
149            6.2           3.4            5.4           2.3          0.0   
150            5.9           3.0            5.1           1.8   

***train_test_split***

The train_test_split function of the sklearn. model_selection package in Python splits arrays or matrices into random subsets for train and test data, respectively.

In [ ]:
from sklearn.model_selection import train_test_split
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [ ]:
print(X)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                           
1              5.1           3.5            1.4           0.2
2              4.9           3.0            1.4           0.2
3              4.7           3.2            1.3           0.2
4              4.6           3.1            1.5           0.2
5              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
146            6.7           3.0            5.2           2.3
147            6.3           2.5            5.0           1.9
148            6.5           3.0            5.2           2.0
149            6.2           3.4            5.4           2.3
150            5.9           3.0            5.1           1.8

[150 rows x 4 columns]


In [ ]:
print(X_train)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                           
119            7.7           2.6            6.9           2.3
19             5.7           3.8            1.7           0.3
5              5.0           3.6            1.4           0.2
46             4.8           3.0            1.4           0.3
60             5.2           2.7            3.9           1.4
..             ...           ...            ...           ...
134            6.3           2.8            5.1           1.5
138            6.4           3.1            5.5           1.8
73             6.3           2.5            4.9           1.5
141            6.7           3.1            5.6           2.4
38             4.9           3.1            1.5           0.1

[105 rows x 4 columns]


In [ ]:
print(X_test)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                           
15             5.8           4.0            1.2           0.2
99             5.1           2.5            3.0           1.1
76             6.6           3.0            4.4           1.4
17             5.4           3.9            1.3           0.4
132            7.9           3.8            6.4           2.0
57             6.3           3.3            4.7           1.6
142            6.9           3.1            5.1           2.3
45             5.1           3.8            1.9           0.4
30             4.7           3.2            1.6           0.2
121            6.9           3.2            5.7           2.3
95             5.6           2.7            4.2           1.3
6              5.4           3.9            1.7           0.4
103            7.1           3.0            5.9           2.1
52             6.4           3.2            4.5           1.5
79      

In [ ]:
print(y)

Id
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
            ...      
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
150    Iris-virginica
Name: Species, Length: 150, dtype: object


In [ ]:
print(y_train)

Id
119     Iris-virginica
19         Iris-setosa
5          Iris-setosa
46         Iris-setosa
60     Iris-versicolor
            ...       
134     Iris-virginica
138     Iris-virginica
73     Iris-versicolor
141     Iris-virginica
38         Iris-setosa
Name: Species, Length: 105, dtype: object


In [ ]:
print(y_test)

Id
15         Iris-setosa
99     Iris-versicolor
76     Iris-versicolor
17         Iris-setosa
132     Iris-virginica
57     Iris-versicolor
142     Iris-virginica
45         Iris-setosa
30         Iris-setosa
121     Iris-virginica
95     Iris-versicolor
6          Iris-setosa
103     Iris-virginica
52     Iris-versicolor
79     Iris-versicolor
43         Iris-setosa
93     Iris-versicolor
67     Iris-versicolor
32         Iris-setosa
36         Iris-setosa
91     Iris-versicolor
85     Iris-versicolor
78     Iris-versicolor
41         Iris-setosa
126     Iris-virginica
100    Iris-versicolor
34         Iris-setosa
20         Iris-setosa
74     Iris-versicolor
147     Iris-virginica
92     Iris-versicolor
136     Iris-virginica
70     Iris-versicolor
129     Iris-virginica
115     Iris-virginica
49         Iris-setosa
54     Iris-versicolor
29         Iris-setosa
55     Iris-versicolor
109     Iris-virginica
113     Iris-virginica
18         Iris-setosa
120     Iris-virginica
104     